### ISSUE TITLE
DPCM Entropy

### ISSUE THREAD

**Issue by bprovot** [eiimage/eiimage#10]
DPCM : calculer et afficher l’entropie de l’image des valeurs de prédiction.

Si on utilise la loi de quantif à 2 niveaux, c'est normal d'avoir un entropie proche de 1 
PB: les valeurs de l'entropie indiquées dans la fenetre de log ne sont pas les mêmes que si on les calcule sur les images à partir du menu tools ; reprendre le code de DoubleEntropyOp pour voir si on obtient le même résultat
- [x] Verifier le code de entropyDouble

**Comment by ARiotte** [comment]
Création d'une fonction getEntropy dans Image.h ce qui permet de centraliser le calcul de l'entropy. 

On facilite alors la correction si besoin / Tous les calcules donnent le même résultat / Eviter de recopier et compliquer le code
