### ISSUE TITLE
Huffman sur des images couleurs

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#101]
Version 2018
Lorsqu'on applique Huffman sur des images couleur, ce n'est pas très clair ce qui est fait.
- visiblement ce n'est pas sur les 3 canaux couleurs mais sur une image en niveau de gris car le débit est de 7
- ce n'est pas sur l'un des caneaux => valeurs min et max non cohérentes
- ce n'est pas sur l'image couleur convertie en niveaux de gris (si on le fait, on n'obtient pas le même résultat)
=> indiquer dans la fenêtre de log ce qui est fait dans ce cas

**Comment by yliu2** [comment]
L'opération Huffman est bien appliqué sur la Grayscale version de l'image d'origine. 
L'incohérence provient d'une erreur de conversion d'image en niveaux de gris, elle a été corrigée.
