### ISSUE TITLE
Boutons - o x manquant

### ISSUE THREAD

**Issue by yliu2** [eiimage/eiimage#102]
<img width="109" alt="prob" src="https://user-images.githubusercontent.com/29675280/104854047-25ded080-5905-11eb-865c-2b00ef342efa.PNG">
Une fois l'image est agrandie, ses boutons en haut à droit ne s'affichent pas correctement. (Ce problème se produit uniquement sur  Windows）

Soit le comportement du QMdiSubWindow à personnalisé dans WindowService.cpp, 
soit cela est lié à la version de Qt avec ses bibliothèques de symboles, j'ai une impression qu'ill peut se résoudre par une compilation sur un autre ordinateur...

Solution à court terme: 
Après avoir ouvert le programme, faites agrandir la première image, puis la réduire, ce problème ne se produira plus jusqu'à la fermeture du programme.

**Comment by TanguyRaufflet** [comment]
Non résolu par une compilation sur un autre PC

**Comment by TanguyRaufflet** [comment]
Le problème n'est pas présent sur la version release de 2018. En revanche, la recompilation de cette version sur mon PC fait apparaître le bug.

**Comment by TanguyRaufflet** [comment]
Le problème provient du style du QApplication défini automatiquement par windows.
Ce style peut être modifié par la commande QApplication::setStyle(QStyleFactory::create("Fusion")); dans main.cpp
