### ISSUE TITLE
Quantificateur Lloyd-Max 

### ISSUE THREAD

**Issue by yliu2** [eiimage/eiimage#103]
Quantificateur Lloyd-Max à implémenter dans le menu DPCM, j'ai complètement supprimé le mien car mon algorithme est incorrect, le programme plantera lors du calcul de certaines size spécifiques.

**Comment by TanguyRaufflet** [comment]
Lloyd-Max ne sera pas implémenté dans le DPCM car il y a une interdépendance entre la quantification et l'algo. de DPCM
