### ISSUE TITLE
Zero-crossing

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#104]
La fonction zero-crossing ne semble pas rendre un résultat correct : sur une image de mire (carré blanc sur fond noir) à laquelle on a appliqué un laplacien, le zero-crossing ne renvoie pas un résultat symétrique.
Donc le traitement n'est pas isotrope.
Attention : le passage par zéro se fait "entre 2 pixels" : il faut choisir pour quel pixel on donne la valeur 255 en sortie.

De plus la fonciton renvoie 2 images : image brute et image nettoyée : un petit message dans la fenêtre d'information sur le nettoyage serait utile (probablement un opérateur de morphomat comme une ouverture)

**Comment by TanguyRaufflet** [comment]
Corrections : 
- Les deux boucles `for` qui permettent de parcourir l'image oubliaient chacunes deux éléments

Avant : 
```
        for(unsigned int j = 2; j < img->getHeight() - 2; ++j) {
            for(unsigned int i = 2; i < img->getWidth() - 2; ++i) {
```
Après : 
```
        for(unsigned int j = 1; j < img->getHeight() - 1; ++j) {
            for(unsigned int i = 1; i < img->getWidth() - 1; ++i) {
```

- Les deux boucles for qui parcourant le voisinage oubliaient chacune un élémént

Avant : 
```

                for(unsigned int k = i-1; k < i+1; ++k) {
                    for(unsigned int l = j-1; l < j+1; ++l) {
```
Après
```
                for(unsigned int k = i-1; k <= i+1; ++k) {
                    for(unsigned int l = j-1; l <= j+1; ++l) {
```

Rq : l'algorithme actuellement implanté ne permet pas de détecter un passage par zero sur les bords de l'image

**Comment by TanguyRaufflet** [comment]
Ajout de la détection sur les bords de l'image : i et j vont à présent de 0 à img->getHeight() - 1 et on fait une vérification dans la suite pour s'assurer que les indices k et l sont dans les limites de l'image via la ligne suivante : 

`if (currentPix <= 0 && neighborPix > 0 && std::abs(currentPix - neighborPix) > threshold)`
