### ISSUE TITLE
DPCM : option no quantization

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#105]
Cette option ne fonctionne pas correctement au vu des différentes images calculées.

**Comment by TanguyRaufflet** [comment]
Le problème venait d'un problème plus général sur le DPCM : l'erreur de prédiction quantifiée n'était pas déterminée correctement. Avec l'option no quantization, on observe à présent que les images de "erreur de prédiction quantifiée" et "erreur de prédiction" sont identiques.
