### ISSUE TITLE
LLoyd-Max optimal quantizer

### ISSUE THREAD

**Issue by bprovot** [eiimage/eiimage#11]
Implémenter un quatificateur optimal (Lloyd-Max) : voir pourquoi plante avec 2 niveaux.
Faire afficher la loi de quantif pour toutes les quatif. 
Remettre les quantif non lineaires dans le menu. 
Tester que les 2 proprietes du quantificateur optimal sont bien verifées
- [x] Find the bug
- [x] Resolve the bug
- [x] Afficher la loi de quantification pour toutes -> fenêtre info
- [x] Tester les deux propriétées -> résultat dans la fenêtre
- [x] Checker si l'algo est bon
- [x] Corriger l'algo/Trouver une condition d'arret 
- [x] Validation

**Comment by ARiotte** [comment]
Choix : condition d'arrêt 
On sort de la boucle quand la moyenne des différences entre les anciens seuils de décision et les nouveaux est inférieur à 1 
On garde la sécurité d'un nombre maximale de boucle de 50 pour éviter les ralentissments (Très grand par rapport au nombre moyen de boucle nécessaire avant convergence : maximum observé jusque là 25)

**Comment by ARiotte** [comment]
Choix : Cas pas d'éléments pour calculer le baricentre
Si il n'y a pas d'éléments dans la zone dont on souhaite calculer le baricentre on choisit de le placer au centre de l'intervalle par défaut.
