### ISSUE TITLE
Tresholding

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#13]
Crash sous linux (et windows ?)  
Raison probable: La fuite mémoire de Histogramme impacte le seuillage qui utilise également la fonction histogramme.

Edit : 
Quand on bouge le curseur du seuil (un seul suffit ) trop vite l'application finit par planter 
- [x] Trouver le problème
- [x] Le corriger

**Comment by bprovot** [comment]
Résolu en même temps que histogram

**Comment by ARiotte** [comment]
Finalement pas complétement résolu

**Comment by bprovot** [comment]
Problème probable: fuite mémoire; pas reproductible sous linux car j'ai 32go de ram, mais si je le fais tourner suffisament longtemps j'imagine que ça crash aussi.

**Comment by ARiotte** [comment]
fuite mémoire dans l'algorithm de binarization le tableau data qui permettait de créer l'image est recopié dans l'image mais l'orginal n'était pas effacé
