### ISSUE TITLE
Hough

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#16]
Hough : modification du pas pour rho et theta a verifier : si on reduit le pas de theta à 0,5, l'intervalle de theta diminue alors qu'il devrait augmenter et les valeurs de theta pour le curseur ne sont pas correctes. A vérifier que pour Hough inverse, cela se passe correctement et que le pas est pris en compte.

Homogénéiser les axes x,y avec le cours (soit dire horizontal, vertical), revoir hough pour avoir memes axes x,y et memes axes rho theta

-Hough : décalage de +1 sur les valeurs de rho affichées (erreur : Y = 256-i au lieu de 255-i ?)
- [x] Changer les axes x,y
- [x] Modification du pas rho et theta Hough
- [x] Pas différent Hough inverse
- [x] Verifier les décalages de +1
- [x] Bug image non carrée
- [x] Inverser champs hauteur largeur dans la fenêtre de sélection hough inverse

**Comment by bprovot** [comment]
Impact du pas, hought inverse

**Comment by bprovot** [comment]
Afficher Rho Tetha dans le nouveau repère

**Comment by ARiotte** [comment]
On utilise maintenant les dimensions données en paramètre pour retrouver le pas utilisé dans la transformée de hough inverse.
Corrige la transformée de hough sur les images non-carrées. 

anciennement : diag = width * Sqrt(2) ;

**Comment by ARiotte** [comment]
Comparaison des nouveaux axes utilisés avec ceux utilisés dans matlab
