### ISSUE TITLE
Filtre

### ISSUE THREAD

**Issue by bprovot** [eiimage/eiimage#23]
Filtre avec des valeurs négatives semblent donner des résultats faux
Se renseigner sur le stretching des valeurs en double
A quoi correspond l'option "offset de 127"

- [x] Suppression de la normalisation systématique
- [x] Indiquer la façon dont est fait le stretching
- [x] Régler le problème des coefs négatifs
- [x] Préparer la mise en place d'un choix de normalisation ou non dans l'algo
- [x] Préparations des options "Offset" et "Scaling"
- [x] Ecrire la formule dans la fenêtre de log

**Comment by ARiotte** [comment]
Reprise du code -> suppression des doublons

**Comment by ARiotte** [comment]
Suppression de la normalisation des coefficients

**Comment by ARiotte** [comment]
Il faudra ajouter un bouton pour  choisir si on veut une normalisation des coeffs ou non

**Comment by ARiotte** [comment]
- Double Résultats corrects 
affichage fait par  la fonction normalize (Image.tpp)
                                     value = (value + offset) * ratio    avec : 
                                     double offset = 0 - MinImage;
                                     double ratio = 255  / (MaxImage - MinImage);

**Comment by ARiotte** [comment]
- Uchar résultat étrange : 
Valeur obtenue par la fonction makeDisplayable (converter.tpp)
Si toute l'image est positive on applique une "normalisation"  val = val * 255 / maxValue 

Si il y a des valeurs négatives on

**Comment by ARiotte** [comment]
La Sortie en Uchar n'a donc pas vraiment de sens
