### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#35]
Après une transformée de hough : 
L'affichage des coordonnées polaire survolées par la souris a des problèmes :
Windows : affichage de valeurs même en dehors de l'image 

Linux : valeurs fausses quand on dezoom

UPDATE: Maintenant le display de pixel est effectif, cependant lorsque l'on sort de coordonnées de l'image, le logiciel continue d'afficher les pixels survolés, en précisant aucune couleur. L'idéal serait que les pixels survolés en dehors de l'image n'affichent rien (aussi bien en couleur qu'en coordonnées), et que les seuls pixels "relevants" soient ceux de l'interieur de l'image.

- [x] Régler les soucis
- [ ] Faire mieux (ne plus display les coordonnées en dehors de l'image)

**Comment by bprovot** [comment]
le fait que les valeurs soient fausses quand on dézoome n'est pas exclusif aux images doubles ou en polaire, ça le fait aussi sur les images simples.
