### ISSUE TITLE
Log Scale

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#57]
Revoir le fonctionnement de la logScale dans les images doubles pour rendre son utilisation plus clair. (Mieux comprendre ce qu'elle fait vraiment , valeurs ?) 

Et améliorer le contraste apporté

**Comment by yliu2** [comment]
logConstant，_logConstantScale et logScale sont combinés dans une relation de produit, mais la moyenne des valeurs (logConstant) est très proche de zéro qui rend les deux autres paramètres perdre leurs rôles de régulateur.
