### ISSUE TITLE
Create basic Element

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#64]
Dans le menu "Element Structurant" de Morpho. Math.

Visualiser le centre de l'element structurant par un carré rouge dans l'interface 

(position du centre : indice pixel =  taille/2 avec division entiere) 

Amélioration à apporter : pouvoir interactivement choisir la position du centre  (clic droit par exemple)

**Comment by TanguyRaufflet** [comment]
Rq : Actuellement, il n'est pas possible de sauvegarder la position du centre de l'ES. L'ES est sauvegardé comme une image en niveau de gris (au format .bmp) mais la classe `StructElem` est définie comme suit : 
` class StructElem  : public GrayscaleImage_t<bool>`

Alors, l'image représentant l'élément structurant ne peut prendre que 0 ou 255 (**bool**) comme valeur. Cela nous empêche d'utiliser une valeur de pixel caractéristique pour désigner le centre de l'élément structurant.
