### ISSUE TITLE
Quantification

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#72]
- Pouvoir quantifier une image double : actuellement, pas de bouton « apply » pour les images de double

- quantification customizée : ne pas limiter les valeurs dans l'intervalle[- 255,255]

**Comment by lucemorin** [comment]
permuter "Custom" et " Lloyd-Max" dans le Menu pour avoir "custom" en dernier

**Comment by TanguyRaufflet** [comment]
Problème pour les quantifications (en dehors de Lloyd-Max) : si l'on met 256 dans number of value, on ne récupère pas l'image originale. Sur une image de mire (centre = 255), le centre se tranforme en une zone de pixel avec comme couleur 1

**Comment by TanguyRaufflet** [comment]
Correctif apporté :  sur toutes les lignes  quant._values[i], retrait du +0.5 qui permettait de faire un arrondi au supérieur. Il n'est pas utile car les valeurs vont bien de 0 à 255 et pas de 1 à 256.
