### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by bprovot** [eiimage/eiimage#75]
Histogramme nécessite de nouvelles fonctionnalités;

- [ ] Zoom sur histogramme
- [ ] Histogramme sur image double: pouvoir choisir la taille des ?bins? (peut-être pouvoir choisir le pas utilisé?)
- [ ] Histogramme cumulé sur image double

**Comment by lucemorin** [comment]
- histogramme

 cumulé du menu contextuel renvoit un résultat erroné

**Comment by yliu2** [comment]
Zoom control of the histogram window enabled by commit 8ce415d.
