### ISSUE TITLE
Morphomath

### ISSUE THREAD

**Issue by bprovot** [eiimage/eiimage#79]
- Améliorer l’ergonomie pour clarifier que la définition de l’élément structurant, matérialiser visuellement le centre de l'élément et pouvoir le déplacer intéractivement

**Comment by TanguyRaufflet** [comment]
- [ ] Dans le menu DMM, sélectionner par défaut DMM et pas érosion
- [ ] Uniformiser l'élement structurant. Actuellement, il y a deux manières de le faire (pas le mêmes couleur, pas les mêmes fonctionnalitées disponible (sauvegarde), ...)

**Comment by TanguyRaufflet** [comment]
- [ ] Finir l'implémentation de la fonctionnalité scale

Cette est partiellement fonctionelle. L'élément structurant appliqué est bien celui affiché (même forme mais plus de pixels) cependant, pour les autres fonctionnalités, l'ES est toujours celui non mis à l'échelle.

Element stuctuant généré : 
![image](https://github.com/eiimage/eiimage/assets/135004418/9ad28f6e-eea3-4544-ada5-d6106cb75e9b)

Element stuctuant sauvegardé : 
![image](https://github.com/eiimage/eiimage/assets/135004418/602738fe-fad4-4f77-a21c-d9034272c3be)

Sélection/déselection de pixel qui se fait par bloc de taille scale*scale + centre de l'ES qui n'a qu'une position possible par bloc : 
![image](https://github.com/eiimage/eiimage/assets/135004418/13513300-73af-47e2-bab8-ed48f9bfa242)

**Comment by TanguyRaufflet** [comment]
La version finale du menu "Element structurant" contient l'ajout de flèches pour dilater l'élément dans la direction désirée (comme dans le menu "DMM") et tous les problèmes évoqués précédemment ont été corrigés (déselection d'un pixel, fonctionnalité "scale", position de l'indicateur du centre de l'ES)
