### ISSUE TITLE
Affichage des images doubles / Fourier Transform

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#81]
Lorsqu’on calcule partie réelle et imaginaire, l'offset est activé automatiquement
TODO : 
-désactiver l'offset par défaut

Si on désactive l'offset dans l'intervalle, on créer une nouvelle image, dont le nom n'est pas clair
TODO : 
-donner un nom plus parlant : conserver (imag) ou (real/réelle)

L'échelle logarithmique ne semble pas fonctionner sur la partie imaginaire, que ce soit avant ou après désactivation de l'offset.

Conclusion : globalement revoir le comportement de l'affichage pour les images doubles avec bouton off set et log scale

**Comment by lucemorin** [comment]
L'échelle logarithmique ne semble pas fonctionner sur la partie immaginaire, que ce soit avant ou après désactivation de l'offset.
globalement revoir le comportement de l'affichage poru els images doubles avec bouton off set et log scale

**Comment by yliu2** [comment]
L'offset par défaut est désormais désactivé et l'échelle logarithmique a été mis à jour pour résoudre le problème des anomalies d'affichage.
