### ISSUE TITLE
TYPOS affichage menus

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#84]
- Menu TSV : nom des images résultat en anglais (titre fenêtre image) => nom dépendant du langage choisi (en Français : Teinte, Saturation, Valeur)
- Menu outil/générer une image RVB : remplacer "RVB" par "couleur" (peut-etre RVB ou TSV à présent).
-Menu "Encodage" : changer en "Codage" / en anglais :  Encoding => Coding
- Menu quantification : mettre Personalisée en dernier (après lloyd-MAx)
- EQM : affichage log : "erreur moyenne". comment est calculée cette valeur? s'agit-il de la racine de l'EQM?
- menu Image/ajouter du bruit/ equart type => ecart type
- transformation d'histogrammes / normalisation
=> modifier en expansion linéaire / linear stretching

**Comment by lucemorin** [comment]
- menu Image/ajouter du bruit/ equart type => ecart type

**Comment by lucemorin** [comment]
transformation d'histogrammes / normalisation
=> modifier en expansion linéaire / linear stretching

**Comment by yliu2** [comment]
Les affichages inappropriés ont été mise à jour
