### ISSUE TITLE
Couleur TSL

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#85]
Génération d'une image TSL

    indiquer dans la fenetre de log la définition de TSL utilisée (via formule ou lien)
    vérifier que cette définition est bien cohérente avec celle utlisée pour la décomposition TSL

**Comment by yliu2** [comment]
Toutes les conversions (la génération, décomposition et combinaison) se font via Qcolor,  elles suivent le même principe. Une petite astuce a été ajoutée à l'interface de génération pour aider à comprendre le plan TSL.
