### ISSUE TITLE
Crash selection image vide

### ISSUE THREAD

**Issue by ARiotte** [eiimage/eiimage#86]
Lorsque l'on essaye se faire une sélection sur une image vide (taille 0x0) le logiciel plante.

Pour recréer ce bug : "générer une image RGB" en laissant les dimensions à 0
Puis essayer de faire une selection dans la fenêtre de l'image (clique enfoncé + déplacement de pointeur)

**Comment by yliu2** [comment]
Fixed by commit 58b4d7a
