### ISSUE TITLE
LUT: Pseudo Colors

### ISSUE THREAD

**Issue by bprovot** [eiimage/eiimage#9]
LUT/Pseudo-couleurs : pouvoir choisir la loi appliquée : nombre de couleurs, voire courbes R,V,B au choix
- [x] Interface
- [x] Algos behind interface
- [x] Traduction de l'interface

**Comment by lucemorin** [comment]
Génération d'une image TSL 
- indiquer dans la fenetre de log la définition de TSL utilisée (via formule ou lien)
- vérifier que cette définition est bien cohérente avec celle utlisée pour la décomposition TSL
