### ISSUE TITLE
Affichage infos de classification incomplet

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#93]
La fonction analyse/classificaiton/option afficher les infos du fichier
affiche dans la fenêtre de log uniquement les moyennes et paramètres et non les variances des paramètres qui sont bien stockées dans le fichier.
=> modifier pour afficher aussi les variances.

**Comment by yliu2** [comment]
Les infors des variance ont été ajoutées dans la fenêtre de log.
