### ISSUE TITLE
Version Linux

### ISSUE THREAD

**Issue by lucemorin** [eiimage/eiimage#96]
Véronique n'a pas réussi a faire fonctionner la version linux avec un étudiant qui avait une machine virtuelle linux sur mac. 
Est-ce qu'on peut vérifier que la version linux fonctionne dans cette configuration?
Il manque aussi un petit readme pour cette config qui pourra être le cas pour les étudiants à distance

**Comment by yliu2** [comment]
Version Linux livrée.
